[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
build_flags = -DDEBUG_ENABLED=0 -Os
lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient  ; MQTT
    ayushsharma82/ElegantOTA

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
build_flags = -I test/stubs -I src -D DEBUG_ENABLED=0
lib_deps = bblanchon/ArduinoJson
test_filter = test_*
targets = test